### ISSUE TITLE
Add Git tags (and GitHub releases)

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [PolymerLabs/note-app-elements#12]
Please add Git tags (and GitHub releases).

If I install bower dependencies for [polymerfire](https://github.com/firebase/polymerfire), I get the following error:

```
bower ENORESTARGET  No tag found that was able to satisfy 1 - 2

Additional error details:
No versions found in https://github.com/polymerlabs/note-app-elements.git
```

**Comment by FluorescentHallucinogen** [comment]
@e111077 PTAL.

**Comment by e111077** [comment]
good point. polymerfire should not have it in the first place, but i think it's important to include version numbers regardless

**Comment by e111077** [comment]
fixed
