### ISSUE TITLE
Probably missing Polymer imports and dependency

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [PolymerLabs/note-app-elements#15]
@e111077 Shouldn't Polymer be imported in `na-behavior.html`, `na-editor.html`, `na-login.html`, `na-note.html` and listed in `bower.json`? :thinking:

**Comment by e111077** [comment]
Typical use cases in the demos and codelab are to import `na-elements.html` which imports polymer. Though I would not be opposed to accepting a PR to change it

**Comment by FluorescentHallucinogen** [comment]
@e111077 PTAL at #16. 😉
