### ISSUE TITLE
Will this be a codelab?

### ISSUE THREAD

**Issue by chiefcll** [PolymerLabs/note-app-elements#8]
Hi Elliot - looking to see if you are going to make this into a 
https://codelabs.developers.google.com/

I'm looking for some more Polymer 2.0 ones to demo.

**Comment by FluorescentHallucinogen** [comment]
@chiefcll, see https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/

**Comment by FluorescentHallucinogen** [comment]
I believe this issue can be closed.

**Comment by e111077** [comment]
@chiefcll as noted above, this repo is already in a codelab (though it is in Polymer 1.0). This does run on Polymer 2.0, but it is only in hybrid mode for now. There is currently no plan to migrate it to ES6 syntax.
